Update main.yml
Signed-off-by: darliiin <117597862+darliiin@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,7 +28,14 @@ jobs:
         cd angular
         npm install
         npm run test -- --watch=false
+      id: start_angular_test
        
+       
+    - name: STOP angular
+      if: steps.start_angular_test.outcome == 'failure'
+      run: |
+        echo "Tests failed, stopping the workflow"
+        exit 1
   
     - name: Build
       run: |
